# .goreleaser.yml
builds:
  -
    main: ./src/main.go
    binary: edgemicroctl
    goos:
      - linux
      - darwin
      - windows
archive:
  name_template: "{{ .ProjectName }}_{{.Tag}}_{{ .Os }}_{{ .Arch }}"
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  wrap_in_directory: true  
  format_overrides:
  - goos: windows
    format: zip
  files:
    - LICENSE
    - README.md
    - NOTICE
    - samples/helloworld/*.yaml
    - samples/httpbin/*.yaml
    - samples/plugin/plugins/response-uppercase/*.*
    - install/kubernetes/*.*
    - install/kubernetes/config/*.yaml
git:
  short_hash: true
release:
  draft: true
  prerelease: true
nfpm:
  name_template: "{{ .ProjectName }}_{{.Tag}}_{{ .Os }}_{{ .Arch }}"
  bindir: bin
